# Census Data Pre-Processing

Import libraries

In [21]:
import pandas as pd
import numpy as np
def dataset(year): return 'Datasets/census/data/ACSDP5Y' + str(year) + '.DP05-Data.csv'

Load dataset and describe

In [22]:
df = pd.read_csv(dataset(2022), low_memory=False)
df = df.iloc[:,:-1] # Drop extra column
df.head()

,GEO_ID,NAME,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,...,DP05_0087PE,DP05_0087PM,DP05_0088PE,DP05_0088PM,DP05_0089PE,DP05_0089PM,DP05_0090PE,DP05_0090PM,DP05_0091PE,DP05_0091PM
0,Geography,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Sex r...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!Total housing units,Percent Margin of Error!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P..."
1,860Z200US00601,ZCTA5 00601,16834,506,8337,227,8497,318,98.1,2.6,...,0.0,0.3,(X),(X),13718,(X),49.2,0.9,50.8,0.9
2,860Z200US00602,ZCTA5 00602,37642,205,18405,84,19237,163,95.7,0.8,...,0.6,0.5,(X),(X),31435,(X),48.7,0.2,51.3,0.2
3,860Z200US00603,ZCTA5 00603,49075,963,23813,585,25262,561,94.3,2.4,...,0.2,0.1,(X),(X),40362,(X),48.0,0.6,52.0,0.6
4,860Z200US00606,ZCTA5 00606,5590,264,2723,216,2867,135,95.0,8.4,...,0.0,0.9,(X),(X),4648,(X),49.6,2.2,50.4,2.2

In [23]:
df.describe()

,GEO_ID,NAME,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,...,DP05_0087PE,DP05_0087PM,DP05_0088PE,DP05_0088PM,DP05_0089PE,DP05_0089PM,DP05_0090PE,DP05_0090PM,DP05_0091PE,DP05_0091PM
count,33775,33775,33775,33775,33775,33775,33775,33775,33775,33775,...,33775,33775,33775,33775,33775,33775,33775,33775,33775,33775
unique,33775,33775,15572,2922,12110,1916,12075,1939,2185,1952,...,334,644,2,2,14102,2,754,559,754,558
top,860Z200US99929,ZCTA5 99929,0,13,0,13,0,13,-,**,...,0.0,1.0,(X),(X),0,(X),-,2.0,-,2.0
freq,1,1,587,261,683,328,744,359,840,840,...,6129,1580,33774,33774,597,33774,597,740,597,740

In [24]:
df.columns = df.iloc[0]
df = df[1:] # Get rid of first header row
df.head()

,Geography,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Margin of Error!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),...,"Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races excluding Some Other Race, and three or more races","Percent Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races excluding Some Other Race, and three or more races",Percent!!Total housing units,Percent Margin of Error!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent Margin of Error!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent Margin of Error!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female","Percent Margin of Error!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
1,860Z200US00601,ZCTA5 00601,16834,506,8337,227,8497,318,98.1,2.6,...,0.0,0.3,(X),(X),13718,(X),49.2,0.9,50.8,0.9
2,860Z200US00602,ZCTA5 00602,37642,205,18405,84,19237,163,95.7,0.8,...,0.6,0.5,(X),(X),31435,(X),48.7,0.2,51.3,0.2
3,860Z200US00603,ZCTA5 00603,49075,963,23813,585,25262,561,94.3,2.4,...,0.2,0.1,(X),(X),40362,(X),48.0,0.6,52.0,0.6
4,860Z200US00606,ZCTA5 00606,5590,264,2723,216,2867,135,95.0,8.4,...,0.0,0.9,(X),(X),4648,(X),49.6,2.2,50.4,2.2
5,860Z200US00610,ZCTA5 00610,25542,344,12317,225,13225,169,93.1,1.5,...,0.1,0.1,(X),(X),21252,(X),47.9,0.5,52.1,0.5

Get the columns we need

In [25]:
# Get percentage columns
df = df.filter(regex='^(Geography|Geographic Area Name|Percent!!)')
df.head()

,Geography,Geographic Area Name,Percent!!SEX AND AGE!!Total population,Percent!!SEX AND AGE!!Total population!!Male,Percent!!SEX AND AGE!!Total population!!Female,Percent!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Percent!!SEX AND AGE!!Total population!!Under 5 years,Percent!!SEX AND AGE!!Total population!!5 to 9 years,Percent!!SEX AND AGE!!Total population!!10 to 14 years,Percent!!SEX AND AGE!!Total population!!15 to 19 years,...,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some Other Race alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races including Some Other Race,"Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races excluding Some Other Race, and three or more races",Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
1,860Z200US00601,ZCTA5 00601,16834,49.5,50.5,(X),3.5,4.3,7.0,6.1,...,0.1,0.0,0.0,0.0,0.0,0.0,(X),13718,49.2,50.8
2,860Z200US00602,ZCTA5 00602,37642,48.9,51.1,(X),3.2,3.9,5.7,5.7,...,0.0,0.0,0.2,0.6,0.0,0.6,(X),31435,48.7,51.3
3,860Z200US00603,ZCTA5 00603,49075,48.5,51.5,(X),3.4,4.3,5.8,6.3,...,0.1,0.0,0.1,0.3,0.1,0.2,(X),40362,48.0,52.0
4,860Z200US00606,ZCTA5 00606,5590,48.7,51.3,(X),3.6,4.3,5.3,5.8,...,0.0,0.0,0.0,0.0,0.0,0.0,(X),4648,49.6,50.4
5,860Z200US00610,ZCTA5 00610,25542,48.2,51.8,(X),3.0,5.1,5.0,5.7,...,0.0,0.0,0.2,0.1,0.0,0.1,(X),21252,47.9,52.1

In [26]:
df.replace("(X)", np.nan, inplace=True)
df = df.dropna(axis=1, how='all')
df.head()

/var/folders/l0/zlzdm20n6vs8qf1px9y10_640000gn/T/ipykernel_59544/3345384310.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("(X)", np.nan, inplace=True)

,Geography,Geographic Area Name,Percent!!SEX AND AGE!!Total population,Percent!!SEX AND AGE!!Total population!!Male,Percent!!SEX AND AGE!!Total population!!Female,Percent!!SEX AND AGE!!Total population!!Under 5 years,Percent!!SEX AND AGE!!Total population!!5 to 9 years,Percent!!SEX AND AGE!!Total population!!10 to 14 years,Percent!!SEX AND AGE!!Total population!!15 to 19 years,Percent!!SEX AND AGE!!Total population!!20 to 24 years,...,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some Other Race alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races including Some Other Race,"Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races excluding Some Other Race, and three or more races","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
1,860Z200US00601,ZCTA5 00601,16834,49.5,50.5,3.5,4.3,7.0,6.1,6.1,...,0.0,0.1,0.0,0.0,0.0,0.0,0.0,13718,49.2,50.8
2,860Z200US00602,ZCTA5 00602,37642,48.9,51.1,3.2,3.9,5.7,5.7,6.2,...,0.1,0.0,0.0,0.2,0.6,0.0,0.6,31435,48.7,51.3
3,860Z200US00603,ZCTA5 00603,49075,48.5,51.5,3.4,4.3,5.8,6.3,6.3,...,0.0,0.1,0.0,0.1,0.3,0.1,0.2,40362,48.0,52.0
4,860Z200US00606,ZCTA5 00606,5590,48.7,51.3,3.6,4.3,5.3,5.8,7.2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4648,49.6,50.4
5,860Z200US00610,ZCTA5 00610,25542,48.2,51.8,3.0,5.1,5.0,5.7,6.5,...,0.0,0.0,0.0,0.2,0.1,0.0,0.1,21252,47.9,52.1

In [27]:
df = df.loc[:, ~df.columns.str.contains('SEX AND AGE')]
df = df.loc[:, ~df.columns.str.contains('CITIZEN')]
list(df.columns)

['Geography',
 'Geographic Area Name',
 'Percent!!RACE!!Total population',
 'Percent!!RACE!!Total population!!One race',
 'Percent!!RACE!!Total population!!Two or More Races',
 'Percent!!RACE!!Total population!!One race',
 'Percent!!RACE!!Total population!!One race!!White',
 'Percent!!RACE!!Total population!!One race!!Black or African American',
 'Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native',
 'Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping',
 'Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping',
 'Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping',
 'Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping',
 'Percent!!RACE!!Total population!!One race!!Asian',
 'Percent!!RACE!!Total population!!One race!!Asian!!Asian Indian',
 'Percent!!RACE!!Total population!!One race!!Asian!!Chinese',
 'Percent!!RACE!!Total population!!One race!!Asian!!Filipino',
 'Percent!!RACE!!Total population!!One race!!Asian!!Japanese',
 'Percent!!RACE!!Total population!!One race!!Asian!!Korean',
 'Percent!!RACE!!Total population!!One race!!Asian!!Vietnamese',
 'Percent!!RACE!!Total population!!One race!!Asian!!Other Asian',
 'Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander',
 'Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Chamorro',
 'Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian',
 'Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan',
 'Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Native Hawaiian and Other Pacific Islander',
 'Percent!!RACE!!Total population!!One race!!Some Other Race',
 'Percent!!RACE!!Total population!!Two or More Races',
 'Percent!!RACE!!Total population!!Two or More Races!!White and Black or African American',
 'Percent!!RACE!!Total population!!Two or More Races!!White and American Indian and Alaska Native',
 'Percent!!RACE!!Total population!!Two or More Races!!White and Asian',
 'Percent!!RACE!!Total population!!Two or More Races!!White and Some Other Race',
 'Percent!!RACE!!Total population!!Two or More Races!!Black or African American and American Indian and Alaska Native',
 'Percent!!RACE!!Total population!!Two or More Races!!Black or African American and Some Other Race',
 'Percent!!Race alone or in combination with one or more other races!!Total population',
 'Percent!!Race alone or in combination with one or more other races!!Total population!!White',
 'Percent!!Race alone or in combination with one or more other races!!Total population!!Black or African American',
 'Percent!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native',
 'Percent!!Race alone or in combination with one or more other races!!Total population!!Asian',
 'Percent!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander',
 'Percent!!Race alone or in combination with one or more other races!!Total population!!Some Other Race',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some Other Race alone',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races including Some Other Race',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races excluding Some Other Race, and three or more races']

In [28]:
df = df[[
    'Geography',
    'Geographic Area Name',
    'Percent!!RACE!!Total population!!One race!!White',
    'Percent!!RACE!!Total population!!One race!!Black or African American',
    'Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native',
    'Percent!!RACE!!Total population!!One race!!Asian',
    'Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander',
    'Percent!!RACE!!Total population!!One race!!Some Other Race',
    'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)'
]]
df.head()

,Geography,Geographic Area Name,Percent!!RACE!!Total population!!One race!!White,Percent!!RACE!!Total population!!One race!!Black or African American,Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native,Percent!!RACE!!Total population!!One race!!Asian,Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander,Percent!!RACE!!Total population!!One race!!Some Other Race,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)
1,860Z200US00601,ZCTA5 00601,84.2,2.1,0.1,0.1,0.0,6.6,99.4
2,860Z200US00602,ZCTA5 00602,49.1,1.5,0.1,0.1,0.0,3.9,94.6
3,860Z200US00603,ZCTA5 00603,73.8,3.5,0.1,0.1,0.0,14.0,98.1
4,860Z200US00606,ZCTA5 00606,66.6,0.2,0.0,0.0,0.0,27.9,99.3
5,860Z200US00610,ZCTA5 00610,43.8,2.3,0.0,0.0,0.0,6.4,96.3